name: FreezeKits
description: This is the description of FreezeKits plugin
version: 2.0
author: GuiDev_
main: Otaku.Main
commands:
  Clan:
  1v1:
  testmacro:
  SetArena:
  efeito3:
  knock:
  mutechat:
  inv:
  v:
  setknock:
  ban:
  kick:
  unban:
  setmlg:
  mlg:
  setkit:
  Morrer:
  tag:
  fly:
  sc:
  gm:
  ajuda:
  set1v1:
  pos1:
  pos2:
  score:
  say:
  SetArena:
  lojahabilit:
  lojaperm:
  mdr:
  setmdr:
  site:
  trial:
  crash:
  SetHg:
  head:
  cc:
  Hg:
  resetkit:
  ban:
  bc:
  tell:
  r:
  money:
  repass:
  report:
  Tp:
  admin:
  feast:
  rfeast:
  setfeast:
  setfps:
  setlava:
  setspawn:
  spawn:
  efeito4:
  efeito5:
  efeito6:
  lava:
  fps:
  rdm:
  setrdm:
  kits:
  kit:
  loja: